### ISSUE TITLE
Custom HEX Language Models Missing

### ISSUE THREAD

**Issue by Maggi9295** [eighttails/ProgramListOCR#4]
I have a hex listing that consists only of characters from 0 to F. However, the 0s have a line through them, and the program isn't able to cope with that. Would it be possible to fix that issue
![ocr](https://user-images.githubusercontent.com/47391654/155370220-b2fc57f9-3b57-4ed4-b18d-d01c1fdb9696.PNG)

**Comment by eighttails** [comment]
You look using deu language model to recognize.
choose hex model from language menu (right of recognize button) and recognize again.

**Comment by Maggi9295** [comment]
I don't seem to have the hex model language... Do I have to install it by hand somehow? I also can't find any of the other language models that should be there in the language settings, only "real" languages.
![ocr2](https://user-images.githubusercontent.com/47391654/155369720-94c6cd12-9b98-468f-9d22-b27370b472d4.png)

**Comment by gingerbeardman** [comment]
@Maggi9295 you can see on [readme page](https://github.com/eighttails/ProgramListOCR/blob/master/README.adoc) that there should be more options in that menu. Did you try reinstalling? Confirm presence of any \*hex\* files in your installation folder.

**Comment by Maggi9295** [comment]
I checked before and after reinstalling, there is only one file with hex in its name, it's this one:
ProgramListOCR\share\tessdata\hex.traineddata
I wasn't able to find any other file named hex.

**Comment by gingerbeardman** [comment]
Interesting. That looks to be fine in terms of files.

I just installed 1.7.1 (32-bit) on a different machine and I get this set of "languages":

<img width="363" alt="Screenshot 2022-02-23 at 20 00 29" src="https://user-images.githubusercontent.com/49612/155398428-918e18ab-941c-4bbd-9889-e22899a070c8.png">

**Comment by gingerbeardman** [comment]
Installation is very simply some 7z files are expanded into the destination directory and some shortcuts set. This is shown in `InstallationLog.txt` in installation directory.

I don't know why gImageReader cannot see your traineddata files.

@Maggi9295 do you see any of the extra languages listed in "Manage languages..."?
(see above screenshot for location of menu item)

**Comment by Maggi9295** [comment]
[InstallationLog.txt](https://github.com/eighttails/ProgramListOCR/files/8127718/InstallationLog.txt)
There seem to be a bunch of Warning messages in the log file. I have checked the Manage language settings, there are none of the languages that should be there, only "real" ones. 
By the way, I use the 64-bit version, not 32-bit.

**Comment by eighttails** [comment]
@Maggi9295 Open preference dialog and make sure "Lauguage data locations" is set to "System-wide paths"
![image](https://user-images.githubusercontent.com/4285709/155422340-1cf1c912-33af-4bcc-a80d-cd0cba81425f.png)
Maybe it references another folder.
Do you have another gImageReader installation in your environment?

**Comment by Maggi9295** [comment]
Yes, thank you so much! It was set to my user-folder or something like that. I set it to sytem-wide and now it works like a charme! Maybe you could add a sentence like "Make sure to set the Language data locations to System-wide paths" to the readme page in case anyone has the same problem?

**Comment by gingerbeardman** [comment]
@Maggi9295 you can suggest the change, press the pencil/edit button on the following page: 
https://github.com/eighttails/ProgramListOCR/blob/master/README.adoc

**Comment by eighttails** [comment]
@Maggi9295 I published version 1.7.2
1.7.1 had a bug that shares registry setting with another gImageReader installation. 
1.7.2 fixes the issue and default setting is suitable for program listings.

**Comment by Maggi9295** [comment]
Great, thank you!
